# Generated by Django 5.2.12 on 2026-03-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicterm',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
